### ISSUE TITLE
sn_main.py run failed in 2010/10 and 2010/11

### ISSUE THREAD

**Issue by uranum12** [uranum12/sunspot#1]
```shell
$ python src/sn_main.py
Traceback (most recent call last):
  File "/sunspot/src/sn_main.py", line 62, in <module>
    main()
  File "/sunspot/src/sn_main.py", line 51, in main
    df, profile = sn_common.sort(all_files).profile()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1563, in profile
    df, timings = ldf.profile()
                  ^^^^^^^^^^^^^
exceptions.ShapeError: unable to vstack, dtypes for column "time" don't match: `str` and `bool`
```

3.11.4 MacOSではエラーが出ない
3.11.4 Linux, 3.11.5 Linux共に上記のエラーが発生

**Comment by uranum12** [comment]
内容が空でも同様のエラーが発生するためファイル名に起因するものと思われる

**Comment by uranum12** [comment]
対象のファイルのみでは失敗しないためファイル数が原因となっているかもしれない

**Comment by uranum12** [comment]
timeをstrからtimeに変え、sortの中のselectを消すことで解決する
